### ISSUE TITLE
mhfu error importing meshes with 4 vertex colors

### ISSUE THREAD

**Issue by Midlex** [AsteriskAmpersand/PMO-Importer#2]
```
Traceback (most recent call last):
  File "C:\...\PMO-Importer-main\operators\importer.py", line 144, in execute
    obj = self.loadMesh(materials,*mesh)
  File "C:\...\PMO-Importer-main\operators\importer.py", line 255, in loadMesh
    self.setColor(mesh,color)
  File "C:\...\PMO-Importer-main\operators\importer.py", line 287, in setColor
    col.color = color[l.vertex_index]
ValueError: bpy_struct: item.attr = val: sequences of dimension 0 should contain 3 items, not 4
```

**Comment by Midlex** [comment]
also can the script be updated to blender 3.0?

**Comment by AsteriskAmpersand** [comment]
Blender 2.79c is required for the fourth vertex color to operate correctly.

**Comment by Midlex** [comment]
Hello, I am now using 2.79b (cant find 2.79c) and still doesnt work.
